In [1]:
import numpy as np

In [2]:
#buat vector x dengan ukuran 3x1
x = np.array([10, 10, 10])
x

array([10, 10, 10])

In [3]:
#hitung panjang vector x
len(x)

3

In [4]:
#tampilkan ukuran vector x
x.shape

(3,)

In [5]:
#tampilkan tipe data dari vector x
type(x)

numpy.ndarray

In [6]:
#akses elemen pertama dari vector x
x[0]

np.int64(10)

In [7]:
#tampilkan tipe data elemen pertama dari vector x
type(x[0])

numpy.int64

In [8]:
#2 lakukan transpose pada vector x dan simpan pada variabel x_t
x_t = x.T
x_t

array([10, 10, 10])

In [9]:
#tampilkan ukuran dari vector x_t
x_t.shape

(3,)

In [20]:
#lakukan transpose pada vector y dan simpan pada variabel y_t
y = np.array([[10, 10, 10]])
y
y_t = y.T
y_t

array([[10],
       [10],
       [10]])

In [21]:
#tampilkan ukuran dari vector y_t
y_t.shape

(3, 1)

lakukan soal nomor 2 menggunakan pytorch dan tensorflow


In [17]:
import torch
import tensorflow as tf

In [23]:
#buat vector x dengan ukuran 3x1
x_pt = torch.tensor([10, 10, 10])
x_pt

tensor([10, 10, 10])

In [24]:
#hitung panjang vector x
len(x_pt)

3

In [25]:
#tampilkan ukuran vector x
x_pt.shape

torch.Size([3])

In [26]:
#tampilkan tipe data dari vector x
type(x_pt)

torch.Tensor

In [27]:
#akses elemen pertama dari vector x
x_pt[0]

tensor(10)

In [28]:
#akses elemen pertama dari vector x
x_pt[0]

tensor(10)

In [29]:
#lakukan transpose pada vector x dan simpan pada variabel x_t
x_pt_t = x_pt
x_pt_t

tensor([10, 10, 10])

In [30]:
#tampilkan ukuran dari vector x_t
x_pt_t.shape

torch.Size([3])

In [31]:
#lakukan transpose pada vector y dan simpan pada variabel y_t
y_pt = np.array([[10, 10, 10]])
y_pt
y_pt_t = y_pt.T
y_pt_t

array([[10],
       [10],
       [10]])

In [32]:
#tampilkan ukuran dari vector y_t
y_pt_t.shape

(3, 1)

TENSORFLOW

In [33]:
#buat vector x dengan ukuran 3x1
x_tf = tf.Variable([10, 10, 10])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([10, 10, 10], dtype=int32)>

In [34]:
#tampilkan ukuran vector x
x_tf.shape

TensorShape([3])

In [35]:
#tampilkan tipe data dari vector x
x_tf.dtype

tf.int32

In [36]:
#akses elemen pertama dari vector x
x_tf[0]

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [37]:
#lakukan transpose pada vector x dan simpan pada variabel x_t
x_tf_t = x_tf
x_tf_t

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([10, 10, 10], dtype=int32)>

In [38]:
#tampilkan ukuran dari vector x_t
x_tf_t.shape

TensorShape([3])

In [40]:
#lakukan transpose pada vector y dan simpan pada variabel y_t
y_tf = np.array([[10, 10, 10]])
y_tf
y_tf_t = y_tf.T
y_tf_t

array([[10],
       [10],
       [10]])

In [41]:
#tampilkan ukuran dari vector y_t
y_tf_t.shape

(3, 1)