In [1]:
import numpy as np

In [2]:
#buat matrix X berukuran 2x3 menggunakan numpy
X = np.array([[10, 10], [10, 10], [10, 10]])
X

array([[10, 10],
       [10, 10],
       [10, 10]])

In [3]:
#tampilkan ukuran dari matrix X
X.shape

(3, 2)

In [4]:
X.size

6

In [5]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X
X[:,0]

array([10, 10, 10])

In [10]:
#tampilkan seluruh elemen dari baris kedua dari matrix X
X[1,:]

array([10, 10])



2.ulangi soal nomor 1 menggunakan pytorch

In [7]:
import torch

In [8]:
#buat matrix X berukuran 2x3 menggunakan numpy
X_pt = torch.tensor([[10, 10], [10, 10], [10, 10]])
X_pt

tensor([[10, 10],
        [10, 10],
        [10, 10]])

In [9]:
#tampilkan ukuran dari matrix X
X_pt.shape

torch.Size([3, 2])

In [11]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X
X_pt[:,0]

tensor([10, 10, 10])

In [16]:
#tampilkan seluruh elemen dari baris kedua dari matrix X
X_pt[1,:]

tensor([10, 10])

ulangi soal nomor 1 menggunakan tensorflow

In [13]:
import tensorflow as tf

In [14]:
#buat matrix X berukuran 2x3 menggunakan numpy
X_tf = tf.Variable([[10, 10], [10, 10], [10, 10]])
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[10, 10],
       [10, 10],
       [10, 10]], dtype=int32)>

In [15]:
#tampilkan ukuran dari matrix X
X_tf.shape

TensorShape([3, 2])

In [17]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X
X_tf[:,0]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 10, 10], dtype=int32)>

In [18]:
#tampilkan seluruh elemen dari baris kedua dari matrix X
X_tf[1,:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>